name: Anguroo Actions Build
on:
  repository_dispatch:
    types: [start_build]
  
jobs:
  Build-Stack-Actions:
    
    runs-on: ubuntu-latest
    env:
      TEMPLATE_PATH: "./types/${{ github.event.client_payload.type }}/${{ github.event.client_payload.framework.name }}"
    strategy:
      matrix:
        node-version: [15.x]
    steps:
      - name: Starting project creation
        uses: actions/checkout@v2
      
    steps:
      - name: "Hello world when it's Monday"
        run: echo "Hello $FIRST_NAME $middle_name $Last_Name, today is Monday!"

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
        if: ${{ github.event.client_payload.framework.name == 'angular' }}
        run: echo "${{ toJson(github.event.client_payload) }}" > ${{env.TEMPLATE_PATH}}/payload.json
        run: npm i  --prefix ${{env.TEMPLATE_PATH}}
        run: npm start --prefix ${{env.TEMPLATE_PATH}}