name: Anguroo Actions Build
on:
  repository_dispatch:
    types: [start_build]
  
jobs:
  Build-Stack-Actions:
    if: ${{ github.event.client_payload.payload.framework.name == 'angular' }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - name: Starting project creation
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm i  --prefix ./types/${{ github.event.client_payload.payload.type }}
      - run: npm start --prefix ./types/${{ github.event.client_payload.payload.type }} -- ${{ github.event.client_payload.base64 }}

      - name: Archive build project
        uses: actions/upload-artifact@v2
        with:
          name: ${{ github.event.client_payload.payload.name }}
          path: ./types/${{ github.event.client_payload.payload.type }}/${{ github.event.client_payload.payload.name }}.zip
          retention-days: 1
      # - name: Send mail
      #   uses: dawidd6/action-send-mail@v3
      #   with:
      #     # Required mail server address:
      #     server_address: smtp.gmail.com
      #     # Required mail server port:
      #     server_port: 465
      #     # Required mail server username:
      #     username: ${{secrets.MAIL_USERNAME}}
      #     # Required mail server password:
      #     password: ${{secrets.MAIL_PASSWORD}}
      #     # Required mail subject:
      #     subject: Github Actions job result
      #     # Required recipients' addresses:
      #     to: ${{ github.event.client_payload.payload.email }}
      #     # Required sender full name (address can be skipped):
      #     from: ${{ secrets.MAIL_USERNAME }} # <user@example.com>
      #     # Optional whether this connection use TLS (default is true if server_port is 465)
      #     secure: true
      #     # Optional plain body:
      #     body: Build job of ${{ github.event.client_payload.payload.name }} completed successfully!
      #     # Optional recipient of the email response:
      #     reply_to: anguroo-project@gmail.com
      #     # Optional unsigned/invalid certificates allowance:
      #     ignore_cert: true
      #     # Optional converting Markdown to HTML (set content_type to text/html too):
      #     convert_markdown: true
      #     # Optional attachments:
      #     attachments: ./types/${{ github.event.client_payload.payload.type }}/${{ github.event.client_payload.payload.name }}.zip