name: Anguroo Actions Build
on:
  repository_dispatch:
    types: [start_build]
  
jobs:
  Build-Stack-Actions:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x, 15.x]
    steps:
      - run: echo "The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "Stating Angular app creation with Anguroo properties for ${{ github.event.client_payload.appName }}"

      - name: Starting project creation
      - uses: actions/checkout@v2
      
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test