name: Anguroo Actions Build
on:
  repository_dispatch:
    types: [start_build]
  
jobs:
  Build-Stack-Actions:
    if: ${{ github.event.client_payload.framework.name == 'angular' }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [15.x]
    steps:
      - name: Starting project creation
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: echo "${{ toJson(github.event.client_payload) }}" > ./types/${{ github.event.client_payload.type }}/${{ github.event.client_payload.framework.name }}/payload.json
      - run: npm i  --prefix ./types/${{ github.event.client_payload.type }}/${{ github.event.client_payload.framework.name }}
      - run: npm start --prefix ./types/${{ github.event.client_payload.type }}/${{ github.event.client_payload.framework.name }}

      # - name: Archive production artifacts
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: dist-without-markdown
      #     path: |
      #       ./types/${{ github.event.client_payload.type }}/${{ github.event.client_payload.framework.name }}/payload.json
