name: Anguroo Actions Build
on:
  repository_dispatch:
    types: [start_build]
  
jobs:
  Build-Stack-Actions:
    if: ${{ github.event.client_payload.payload.framework.name == 'angular' }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - name: Starting project creation
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm i  --prefix ./types/${{ github.event.client_payload.payload.type }}
      - run: npm start --prefix ./types/${{ github.event.client_payload.payload.type }} -- ${{ github.event.client_payload.base64 }}